const userStructure = [
  {
    token: '45erkjherht45495783',
    id: 1,
    email: 'chuku.omoke@gmail.com',
    firstName: 'Omoke',
    lastName: 'Chuku',
    password: '',
    address: 'Epic Tower Nigeria',
    status: 'verified',
    isAdmin: false,
  },
  {
    token: '45erkjherht45495783',
    id: 2,
    email: 'omoke.chuku@gmail.com',
    firstName: 'David',
    lastName: 'Omoke',
    password: '',
    address: 'Kauraas, F.C.T, Abuja',
    status: 'unverified',
    isAdmin: false,
  },
  {
    token: '45erkjherht45495783',
    id: 3,
    email: 'omoke.chuku2@gmail.com',
    firstName: 'Chuku',
    lastName: 'Chuku',
    password: '',
    address: 'Kauraee, F.C.T, Abuja',
    status: 'unverified',
    isAdmin: false,
  },
  {
    token: '45erkjherht45495783',
    id: 4,
    email: 'omoke.chuku3@gmail.com',
    firstName: 'David',
    lastName: 'Chalu',
    password: '',
    address: 'Kaurwa, F.C.T, Abuja',
    status: 'unverified',
    isAdmin: false,
  },
  {
    token: '45erkjherht45495783',
    id: 5,
    email: 'omoke.chuku4@gmail.com',
    firstName: 'Chalu',
    lastName: 'Chuku',
    password: '',
    address: 'Kauras, F.C.T, Abuja',
    status: 'unverified',
    isAdmin: false,
  },
  {
    token: '45erkjherht45495783',
    id: 6,
    email: 'omoke.chuku5@gmail.com',
    firstName: 'Omoke',
    lastName: 'Davo',
    password: '',
    address: 'Kauraa, F.C.T, Abuja',
    status: 'unverified',
    isAdmin: false,
  },
];

export default userStructure;
